import type { AllUsersRecord, AllUsersStats } from './allUsers.types';

export const SAMPLE_USERS: AllUsersRecord[] = [
  {
    id: 'USR-10001',
    avatarUrl: null,
    name: 'Priya Sharma',
    username: 'priya.sharma',
    email: 'priya.sharma@example.com',
    phone: '+91 98765 43210',
    roles: ['reader', 'author'],
    status: 'active',
    membership: 'premium',
    verification: 'verified',
    books: 12,
    blogs: 8,
    articles: 4,
    stories: 2,
    poems: 6,
    orders: 24,
    walletBalance: 1250,
    country: 'India',
    state: 'Maharashtra',
    city: 'Pune',
    lastLogin: '2026-07-07T08:15:00Z',
    createdAt: '2024-03-12T10:00:00Z',
    isNewToday: false,
    isActiveToday: true,
  },
  {
    id: 'USR-10002',
    avatarUrl: null,
    name: 'Rahul Kulkarni',
    username: 'rahul.k',
    email: 'rahul.k@example.com',
    phone: '+91 91234 56789',
    roles: ['reader'],
    status: 'active',
    membership: 'free',
    verification: 'verified',
    books: 0,
    blogs: 0,
    articles: 0,
    stories: 0,
    poems: 0,
    orders: 3,
    walletBalance: 0,
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    lastLogin: '2026-07-07T06:42:00Z',
    createdAt: '2025-11-20T14:30:00Z',
    isNewToday: false,
    isActiveToday: true,
  },
  {
    id: 'USR-10003',
    avatarUrl: null,
    name: 'Javed Kulkarni',
    username: 'javed.kulkarni',
    email: 'jaavedkulkarni@gmail.com',
    phone: '+91 99887 76655',
    roles: ['super_admin', 'reader'],
    status: 'active',
    membership: 'lifetime',
    verification: 'verified',
    books: 45,
    blogs: 32,
    articles: 18,
    stories: 9,
    poems: 14,
    orders: 0,
    walletBalance: 0,
    country: 'India',
    state: 'Maharashtra',
    city: 'Pune',
    lastLogin: '2026-07-07T09:00:00Z',
    createdAt: '2023-01-01T00:00:00Z',
    isNewToday: false,
    isActiveToday: true,
  },
  {
    id: 'USR-10004',
    avatarUrl: null,
    name: 'Anita Desai',
    username: 'anita.desai',
    email: 'anita.desai@example.com',
    phone: '+91 90123 45678',
    roles: ['publisher', 'reader'],
    status: 'active',
    membership: 'basic',
    verification: 'verified',
    books: 0,
    blogs: 0,
    articles: 0,
    stories: 0,
    poems: 0,
    orders: 1,
    walletBalance: 500,
    country: 'India',
    state: 'Gujarat',
    city: 'Ahmedabad',
    lastLogin: '2026-07-06T18:20:00Z',
    createdAt: '2025-06-15T09:00:00Z',
    isNewToday: false,
    isActiveToday: false,
  },
  {
    id: 'USR-10005',
    avatarUrl: null,
    name: 'Vikram Patil',
    username: 'vikram.p',
    email: 'vikram.p@example.com',
    phone: '+91 87654 32109',
    roles: ['admin', 'reader'],
    status: 'active',
    membership: 'premium',
    verification: 'verified',
    books: 0,
    blogs: 0,
    articles: 0,
    stories: 0,
    poems: 0,
    orders: 0,
    walletBalance: 0,
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
    lastLogin: '2026-07-07T07:30:00Z',
    createdAt: '2024-08-01T11:00:00Z',
    isNewToday: false,
    isActiveToday: true,
  },
  {
    id: 'USR-10006',
    avatarUrl: null,
    name: 'Sneha Reddy',
    username: 'sneha.reddy',
    email: 'sneha.reddy@example.com',
    phone: '+91 88990 11223',
    roles: ['author', 'reader'],
    status: 'suspended',
    membership: 'basic',
    verification: 'verified',
    books: 5,
    blogs: 3,
    articles: 1,
    stories: 0,
    poems: 2,
    orders: 8,
    walletBalance: 320,
    country: 'India',
    state: 'Telangana',
    city: 'Hyderabad',
    lastLogin: '2026-06-28T12:00:00Z',
    createdAt: '2025-02-10T08:00:00Z',
    isNewToday: false,
    isActiveToday: false,
  },
  {
    id: 'USR-10007',
    avatarUrl: null,
    name: 'Arjun Mehta',
    username: 'arjun.m',
    email: 'arjun.m@example.com',
    phone: '+91 77889 99001',
    roles: ['reader'],
    status: 'blocked',
    membership: 'free',
    verification: 'rejected',
    books: 0,
    blogs: 0,
    articles: 0,
    stories: 0,
    poems: 0,
    orders: 0,
    walletBalance: 0,
    country: 'India',
    state: 'Delhi',
    city: 'New Delhi',
    lastLogin: '2026-05-01T10:00:00Z',
    createdAt: '2025-09-05T16:00:00Z',
    isNewToday: false,
    isActiveToday: false,
  },
  {
    id: 'USR-10008',
    avatarUrl: null,
    name: 'Kavita Joshi',
    username: 'kavita.j',
    email: 'kavita.j@example.com',
    phone: '+91 66778 88990',
    roles: ['reader'],
    status: 'pending',
    membership: 'free',
    verification: 'pending',
    books: 0,
    blogs: 0,
    articles: 0,
    stories: 0,
    poems: 0,
    orders: 0,
    walletBalance: 0,
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    lastLogin: '—',
    createdAt: '2026-07-07T05:00:00Z',
    isNewToday: true,
    isActiveToday: true,
  },
  {
    id: 'USR-10009',
    avatarUrl: null,
    name: 'Mohammed Ali',
    username: 'm.ali',
    email: 'm.ali@example.com',
    phone: '+91 55667 77889',
    roles: ['author', 'reader'],
    status: 'active',
    membership: 'premium',
    verification: 'verified',
    books: 8,
    blogs: 15,
    articles: 6,
    stories: 4,
    poems: 3,
    orders: 12,
    walletBalance: 890,
    country: 'India',
    state: 'Kerala',
    city: 'Kochi',
    lastLogin: '2026-07-07T04:10:00Z',
    createdAt: '2024-11-22T13:00:00Z',
    isNewToday: false,
    isActiveToday: true,
  },
  {
    id: 'USR-10010',
    avatarUrl: null,
    name: 'Deepa Nair',
    username: 'deepa.nair',
    email: 'deepa.nair@example.com',
    phone: '+91 44556 66778',
    roles: ['reader'],
    status: 'active',
    membership: 'basic',
    verification: 'unverified',
    books: 0,
    blogs: 0,
    articles: 0,
    stories: 0,
    poems: 0,
    orders: 2,
    walletBalance: 150,
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Chennai',
    lastLogin: '2026-07-05T20:00:00Z',
    createdAt: '2026-01-18T10:00:00Z',
    isNewToday: false,
    isActiveToday: false,
  },
];

export function computeSampleStats(users: AllUsersRecord[]): AllUsersStats {
  return {
    totalUsers: users.length,
    readers: users.filter((u) => u.roles.includes('reader')).length,
    authors: users.filter((u) => u.roles.includes('author')).length,
    publishers: users.filter((u) => u.roles.includes('publisher')).length,
    platformAdmins: users.filter((u) => u.roles.includes('admin')).length,
    superAdmins: users.filter((u) => u.roles.includes('super_admin')).length,
    newToday: users.filter((u) => u.isNewToday).length,
    activeToday: users.filter((u) => u.isActiveToday).length,
  };
}

export const SAVED_FILTER_PRESETS = [
  { id: 'my-authors', label: 'My Authors' },
  { id: 'premium', label: 'Premium Users' },
  { id: 'suspended', label: 'Suspended Users' },
  { id: 'blocked', label: 'Blocked Users' },
  { id: 'pending-verification', label: 'Pending Verification' },
];

export const PAGE_SIZE_OPTIONS = [10, 25, 50, 100, 250, 500] as const;
