import type { ErrorCatalogEntry } from './error.types';

const DOC = (code: string) => `#${code}` as const;

export const ERROR_CATALOG = {
  AUTH_001: {
    code: 'AUTH_001',
    domain: 'AUTH',
    message: 'Authentication required',
    httpStatus: 401,
    severity: 'warning',
    recoveryStrategy: 'Sign in and retry the request with a valid session token.',
    documentationPath: DOC('AUTH_001'),
  },
  AUTH_002: {
    code: 'AUTH_002',
    domain: 'AUTH',
    message: 'Session expired',
    httpStatus: 401,
    severity: 'warning',
    recoveryStrategy: 'Sign in again to obtain a fresh session.',
    documentationPath: DOC('AUTH_002'),
  },
  AUTH_003: {
    code: 'AUTH_003',
    domain: 'AUTH',
    message: 'Invalid credentials',
    httpStatus: 401,
    severity: 'warning',
    recoveryStrategy: 'Verify email and password, then retry.',
    documentationPath: DOC('AUTH_003'),
  },
  USER_001: {
    code: 'USER_001',
    domain: 'USER',
    message: 'User not found',
    httpStatus: 404,
    severity: 'error',
    recoveryStrategy: 'Verify the user identifier and retry.',
    documentationPath: DOC('USER_001'),
  },
  USER_002: {
    code: 'USER_002',
    domain: 'USER',
    message: 'User already exists',
    httpStatus: 409,
    severity: 'warning',
    recoveryStrategy: 'Use a different email or restore an existing account.',
    documentationPath: DOC('USER_002'),
  },
  USER_003: {
    code: 'USER_003',
    domain: 'USER',
    message: 'User account is suspended',
    httpStatus: 403,
    severity: 'warning',
    recoveryStrategy: 'Contact platform support to restore access.',
    documentationPath: DOC('USER_003'),
  },
  ROLE_001: {
    code: 'ROLE_001',
    domain: 'ROLE',
    message: 'Insufficient permissions',
    httpStatus: 403,
    severity: 'warning',
    recoveryStrategy: 'Request the required role from a platform administrator.',
    documentationPath: DOC('ROLE_001'),
  },
  ROLE_002: {
    code: 'ROLE_002',
    domain: 'ROLE',
    message: 'Role assignment failed',
    httpStatus: 409,
    severity: 'error',
    recoveryStrategy: 'Verify role name and target user, then retry.',
    documentationPath: DOC('ROLE_002'),
  },
  BOOK_001: {
    code: 'BOOK_001',
    domain: 'BOOK',
    message: 'Book not found',
    httpStatus: 404,
    severity: 'error',
    recoveryStrategy: 'Verify book identifier and catalog visibility.',
    documentationPath: DOC('BOOK_001'),
  },
  BOOK_002: {
    code: 'BOOK_002',
    domain: 'BOOK',
    message: 'Book is not published',
    httpStatus: 403,
    severity: 'warning',
    recoveryStrategy: 'Publish the book or use a preview entitlement.',
    documentationPath: DOC('BOOK_002'),
  },
  CMS_001: {
    code: 'CMS_001',
    domain: 'CMS',
    message: 'CMS resource not found',
    httpStatus: 404,
    severity: 'error',
    recoveryStrategy: 'Verify CMS resource identifier and retry.',
    documentationPath: DOC('CMS_001'),
  },
  CMS_002: {
    code: 'CMS_002',
    domain: 'CMS',
    message: 'CMS operation not permitted',
    httpStatus: 403,
    severity: 'warning',
    recoveryStrategy: 'Ensure CMS feature flag and staff permissions are enabled.',
    documentationPath: DOC('CMS_002'),
  },
  ORDER_001: {
    code: 'ORDER_001',
    domain: 'ORDER',
    message: 'Order not found',
    httpStatus: 404,
    severity: 'error',
    recoveryStrategy: 'Verify order identifier and ownership.',
    documentationPath: DOC('ORDER_001'),
  },
  ORDER_002: {
    code: 'ORDER_002',
    domain: 'ORDER',
    message: 'Order cannot be modified in current state',
    httpStatus: 409,
    severity: 'warning',
    recoveryStrategy: 'Review order status and use the appropriate workflow action.',
    documentationPath: DOC('ORDER_002'),
  },
  PAYMENT_001: {
    code: 'PAYMENT_001',
    domain: 'PAYMENT',
    message: 'Payment processing failed',
    httpStatus: 402,
    severity: 'error',
    recoveryStrategy: 'Verify payment method and retry checkout.',
    documentationPath: DOC('PAYMENT_001'),
  },
  PAYMENT_002: {
    code: 'PAYMENT_002',
    domain: 'PAYMENT',
    message: 'Payments feature is disabled',
    httpStatus: 503,
    severity: 'info',
    recoveryStrategy: 'Enable payments feature flag or wait for platform activation.',
    documentationPath: DOC('PAYMENT_002'),
  },
  SYSTEM_001: {
    code: 'SYSTEM_001',
    domain: 'SYSTEM',
    message: 'Validation failed',
    httpStatus: 400,
    severity: 'warning',
    recoveryStrategy: 'Correct input fields and retry.',
    documentationPath: DOC('SYSTEM_001'),
  },
  SYSTEM_002: {
    code: 'SYSTEM_002',
    domain: 'SYSTEM',
    message: 'Rate limit exceeded',
    httpStatus: 429,
    severity: 'warning',
    recoveryStrategy: 'Wait for Retry-After interval, then retry.',
    documentationPath: DOC('SYSTEM_002'),
  },
  SYSTEM_003: {
    code: 'SYSTEM_003',
    domain: 'SYSTEM',
    message: 'Internal server error',
    httpStatus: 500,
    severity: 'critical',
    recoveryStrategy: 'Retry later. Contact support if the issue persists.',
    documentationPath: DOC('SYSTEM_003'),
  },
  STORAGE_001: {
    code: 'STORAGE_001',
    domain: 'STORAGE',
    message: 'File upload failed',
    httpStatus: 400,
    severity: 'error',
    recoveryStrategy: 'Verify file type, size, and bucket permissions.',
    documentationPath: DOC('STORAGE_001'),
  },
  EDGE_001: {
    code: 'EDGE_001',
    domain: 'EDGE',
    message: 'Edge function invocation failed',
    httpStatus: 502,
    severity: 'error',
    recoveryStrategy: 'Retry the request. Verify network connectivity.',
    documentationPath: DOC('EDGE_001'),
  },
  EDGE_002: {
    code: 'EDGE_002',
    domain: 'EDGE',
    message: 'Idempotency key conflict',
    httpStatus: 409,
    severity: 'warning',
    recoveryStrategy: 'Use a new idempotency key or reuse the same payload.',
    documentationPath: DOC('EDGE_002'),
  },
} as const satisfies Record<string, ErrorCatalogEntry>;

export type ErrorCatalogCode = keyof typeof ERROR_CATALOG;

export const ERROR_CATALOG_CODES = Object.keys(ERROR_CATALOG) as ErrorCatalogCode[];
