import {
  BarChart3,
  BookOpen,
  FileText,
  FolderOpen,
  Image,
  PenTool,
  ScrollText,
  User,
  Wallet,
} from 'lucide-react';
import { PERMISSIONS } from '../roles/types/permission.types';
import { defineNavigationItem } from './types';
import type { NavigationItem } from './types';

const AUTHOR_CONTENT_CHILDREN: NavigationItem[] = [
  defineNavigationItem({
    id: 'author-books',
    title: 'Books',
    icon: BookOpen,
    path: '/author/books',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.books.view],
    sortOrder: 210,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-blogs',
    title: 'Blogs',
    icon: PenTool,
    path: '/author/blogs',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.blogs.view],
    sortOrder: 220,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-articles',
    title: 'Articles',
    icon: FileText,
    path: '/author/articles',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.blogs.view],
    sortOrder: 230,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-stories',
    title: 'Stories',
    icon: ScrollText,
    path: '/author/stories',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.blogs.view],
    sortOrder: 240,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-poems',
    title: 'Poems',
    icon: FileText,
    path: '/author/poems',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.blogs.view],
    sortOrder: 250,
    section: 'author',
  }),
];

/** Author role additions merged on top of reader navigation. */
export const AUTHOR_NAVIGATION: NavigationItem[] = [
  defineNavigationItem({
    id: 'author-content-group',
    title: 'Content',
    icon: FolderOpen,
    path: '/author/books',
    children: AUTHOR_CONTENT_CHILDREN,
    requiredRoles: ['author'],
    sortOrder: 200,
    section: 'author',
  }),
  ...AUTHOR_CONTENT_CHILDREN,
  defineNavigationItem({
    id: 'author-media-library',
    title: 'Media Library',
    icon: Image,
    path: '/author/media',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.media.view],
    sortOrder: 260,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-analytics',
    title: 'Analytics',
    icon: BarChart3,
    path: '/author/analytics',
    requiredRoles: ['author'],
    requiredPermissions: [PERMISSIONS.author.analytics.view],
    sortOrder: 270,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-earnings',
    title: 'Earnings',
    icon: Wallet,
    path: '/author/earnings',
    requiredRoles: ['author'],
    sortOrder: 280,
    section: 'author',
  }),
  defineNavigationItem({
    id: 'author-profile',
    title: 'Author Profile',
    icon: User,
    path: '/author/profile',
    requiredRoles: ['author'],
    sortOrder: 290,
    section: 'author',
  }),
];
