import {
  Bell,
  ClipboardList,
  HelpCircle,
  LayoutDashboard,
  Package,
  Receipt,
  Search,
  Truck,
  User,
  UserCircle,
} from 'lucide-react';
import { PERMISSIONS } from '../roles/types/permission.types';
import { defineNavigationItem } from './types';
import type { NavigationItem } from './types';

const PUBLISHER_BASE_PATH = '/publisher';

/** Publisher role navigation — independent surface without reader inheritance. */
export const PUBLISHER_NAVIGATION: NavigationItem[] = [
  defineNavigationItem({
    id: 'publisher-dashboard',
    title: 'Dashboard',
    icon: LayoutDashboard,
    path: PUBLISHER_BASE_PATH,
    requiredRoles: ['publisher'],
    sortOrder: 600,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-notifications',
    title: 'Notifications',
    icon: Bell,
    path: `${PUBLISHER_BASE_PATH}/notifications`,
    requiredRoles: ['publisher'],
    sortOrder: 610,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-search',
    title: 'Search',
    icon: Search,
    path: `${PUBLISHER_BASE_PATH}/search`,
    action: 'search',
    requiredRoles: ['publisher'],
    sortOrder: 620,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-profile',
    title: 'Profile',
    icon: User,
    path: `${PUBLISHER_BASE_PATH}/profile`,
    requiredRoles: ['publisher'],
    sortOrder: 630,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-account',
    title: 'Account',
    icon: UserCircle,
    path: `${PUBLISHER_BASE_PATH}/account`,
    requiredRoles: ['publisher'],
    sortOrder: 640,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-help',
    title: 'Help',
    icon: HelpCircle,
    path: `${PUBLISHER_BASE_PATH}/help`,
    requiredRoles: ['publisher'],
    sortOrder: 650,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-rfqs',
    title: 'RFQs',
    icon: ClipboardList,
    path: `${PUBLISHER_BASE_PATH}/rfq`,
    requiredRoles: ['publisher'],
    requiredPermissions: [PERMISSIONS.publisher.rfq.view],
    sortOrder: 660,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-jobs',
    title: 'Jobs',
    icon: ClipboardList,
    path: `${PUBLISHER_BASE_PATH}/jobs`,
    requiredRoles: ['publisher'],
    requiredPermissions: [PERMISSIONS.publisher.jobs.view],
    sortOrder: 670,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-production',
    title: 'Production',
    icon: Package,
    path: `${PUBLISHER_BASE_PATH}/production`,
    requiredRoles: ['publisher'],
    requiredPermissions: [PERMISSIONS.publisher.jobs.manage],
    sortOrder: 680,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-dispatch',
    title: 'Dispatch',
    icon: Truck,
    path: `${PUBLISHER_BASE_PATH}/dispatch`,
    requiredRoles: ['publisher'],
    requiredPermissions: [PERMISSIONS.publisher.jobs.view],
    sortOrder: 690,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-tracking',
    title: 'Tracking',
    icon: Truck,
    path: `${PUBLISHER_BASE_PATH}/tracking`,
    requiredRoles: ['publisher'],
    requiredPermissions: [PERMISSIONS.publisher.jobs.view],
    sortOrder: 700,
    section: 'publisher',
  }),
  defineNavigationItem({
    id: 'publisher-billing',
    title: 'Billing',
    icon: Receipt,
    path: `${PUBLISHER_BASE_PATH}/billing`,
    requiredRoles: ['publisher'],
    requiredPermissions: [PERMISSIONS.publisher.quotes.view],
    sortOrder: 710,
    section: 'publisher',
  }),
];
