import {
  BarChart3,
  Building2,
  Database,
  GitBranch,
  Image,
  KeyRound,
  LayoutDashboard,
  Lock,
  PenTool,
  Plug,
  Settings,
  Shield,
  Users,
  Wrench,
} from 'lucide-react';
import { PERMISSIONS } from '../roles/types/permission.types';
import { SUPER_ADMIN_BASE_PATH } from '../super-admin/constants/superAdmin.constants';
import { defineNavigationItem } from './types';
import type { NavigationItem } from './types';

/** Super admin role additions for full platform control. */
export const SUPER_ADMIN_NAVIGATION: NavigationItem[] = [
  defineNavigationItem({
    id: 'super-admin-user-management',
    title: 'User Management',
    icon: Users,
    path: `${SUPER_ADMIN_BASE_PATH}/people`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.users.view],
    sortOrder: 400,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-role-management',
    title: 'Role Management',
    icon: Shield,
    path: `${SUPER_ADMIN_BASE_PATH}/roles`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.users.manage],
    sortOrder: 410,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-permission-management',
    title: 'Permission Management',
    icon: KeyRound,
    path: `${SUPER_ADMIN_BASE_PATH}/permissions`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.users.manage],
    sortOrder: 420,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-organization-management',
    title: 'Organization Management',
    icon: Building2,
    path: `${SUPER_ADMIN_BASE_PATH}/organizations`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.manage],
    sortOrder: 430,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-author-management',
    title: 'Author Management',
    icon: PenTool,
    path: `${SUPER_ADMIN_BASE_PATH}/authors`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.users.view],
    sortOrder: 440,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-publisher-management',
    title: 'Publisher Management',
    icon: Building2,
    path: `${SUPER_ADMIN_BASE_PATH}/publishers`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.users.view],
    sortOrder: 450,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-platform-settings',
    title: 'Platform Settings',
    icon: Settings,
    path: `${SUPER_ADMIN_BASE_PATH}/platform`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.settings.view],
    sortOrder: 460,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-security',
    title: 'Security',
    icon: Lock,
    path: `${SUPER_ADMIN_BASE_PATH}/security`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.manage],
    sortOrder: 470,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-audit-logs',
    title: 'Audit Logs',
    icon: Shield,
    path: `${SUPER_ADMIN_BASE_PATH}/security/audit`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.manage],
    sortOrder: 480,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-platform-analytics',
    title: 'Platform Analytics',
    icon: BarChart3,
    path: `${SUPER_ADMIN_BASE_PATH}/analytics`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.view],
    sortOrder: 490,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-system-maintenance',
    title: 'System Maintenance',
    icon: Wrench,
    path: `${SUPER_ADMIN_BASE_PATH}/maintenance`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.manage],
    sortOrder: 500,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-integrations',
    title: 'Integrations',
    icon: Plug,
    path: `${SUPER_ADMIN_BASE_PATH}/integrations`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.settings.manage],
    sortOrder: 510,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-media-library',
    title: 'Media Library',
    icon: Image,
    path: `${SUPER_ADMIN_BASE_PATH}/media`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.view],
    sortOrder: 520,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-navigation-manager',
    title: 'Navigation Manager',
    icon: LayoutDashboard,
    path: `${SUPER_ADMIN_BASE_PATH}/navigation`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.settings.manage],
    sortOrder: 530,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-workflow-manager',
    title: 'Workflow Manager',
    icon: GitBranch,
    path: `${SUPER_ADMIN_BASE_PATH}/workflows`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.settings.manage],
    sortOrder: 540,
    section: 'super_admin',
  }),
  defineNavigationItem({
    id: 'super-admin-backup-restore',
    title: 'Backup & Restore',
    icon: Database,
    path: `${SUPER_ADMIN_BASE_PATH}/backup`,
    requiredRoles: ['super_admin'],
    requiredPermissions: [PERMISSIONS.super.platform.manage],
    sortOrder: 550,
    section: 'super_admin',
  }),
];
