import {
  CREATE_USER_INPUT_CLASS,
  CREATE_USER_LABEL_CLASS,
  CREATE_USER_SECTION_CLASS,
  CREATE_USER_ERROR_CLASS,
  CREATE_USER_LANGUAGE_OPTIONS,
  CREATE_USER_TIMEZONE_OPTIONS,
  CREATE_USER_STATUS_OPTIONS,
} from '../create-user/create-user.constants';

export const EDIT_USER_FORM_ID = 'edit-user-form';

export const EDIT_USER_UNSAVED_MESSAGE =
  'You have unsaved changes. Discard them and close the drawer?';

export const EDIT_USER_DRAWER_MAX_WIDTH = 'max-w-3xl';

export {
  CREATE_USER_INPUT_CLASS as EDIT_USER_INPUT_CLASS,
  CREATE_USER_LABEL_CLASS as EDIT_USER_LABEL_CLASS,
  CREATE_USER_SECTION_CLASS as EDIT_USER_SECTION_CLASS,
  CREATE_USER_ERROR_CLASS as EDIT_USER_ERROR_CLASS,
  CREATE_USER_LANGUAGE_OPTIONS as EDIT_USER_LANGUAGE_OPTIONS,
  CREATE_USER_TIMEZONE_OPTIONS as EDIT_USER_TIMEZONE_OPTIONS,
  CREATE_USER_STATUS_OPTIONS as EDIT_USER_STATUS_OPTIONS,
};
